### PR TITLE
toplevel changes

### PR DESCRIPTION
**Pull request by kenichi**
- move filters to DSL - i tried angelo-ws-heroku and it uses before which i think should be there
- add test:main rake task - exclude main from default, add separate task for that
- run main test on lo0 - see note about bizarre 127 address :smiley_cat:

### CODE REVIEW

**Comment by kenichi** [comment]
note: i've altered and deployed https://github.com/kenichi/angelo-ws-heroku/blob/toplevel/chatdemo.rb

it is running at https://angelo-test.herokuapp.com

**Comment by tommay** [comment]
It doesn't look like filters, filter, and filter_by should be in module DSL.  Right?  Wrong?

And what's the rationale for moving the main tests to a new rake task?

**Comment by tommay** [comment]
I had fun chatting with myself until I realized I was a boring conversationalist who can't type worth a crap.

**Comment by kenichi** [comment]
derp, i grabbed some extra methods there. also, for some reason, i had it in my brainhole that main needed to run separately. sigh.

**Pull request closed without merging**
